-- -------------------------------------------------------------
-- TablePlus 4.6.4(414)
--
-- https://tableplus.com/
--
-- Database: bagisto
-- Generation Time: 2022-04-18 06:20:06.1460
-- -------------------------------------------------------------


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


DROP TABLE IF EXISTS `settings`;
CREATE TABLE `settings` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `key` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `value` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `settings_key_unique` (`key`)
) ENGINE=InnoDB AUTO_INCREMENT=294 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES
(1, 'activated_plugins', '[\"language\",\"language-advanced\",\"ads\",\"analytics\",\"audit-log\",\"backup\",\"blog\",\"captcha\",\"contact\",\"cookie-consent\",\"ecommerce\",\"faq\",\"marketplace\",\"mollie\",\"newsletter\",\"payment\",\"paystack\",\"razorpay\",\"simple-slider\",\"social-login\",\"sslcommerz\",\"translation\",\"location\"]', NULL, NULL),
(2, 'payment_cod_status', '1', NULL, NULL),
(3, 'payment_bank_transfer_status', '1', NULL, NULL),
(4, 'simple_slider_using_assets', '0', NULL, NULL),
(5, 'permalink-botble-blog-models-post', 'blog', NULL, NULL),
(6, 'permalink-botble-blog-models-category', 'blog', NULL, NULL),
(7, 'payment_cod_description', 'Please pay money directly to the postman, if you choose cash on delivery method (COD).', NULL, NULL),
(8, 'payment_bank_transfer_description', 'Please send money to our bank account: ACB - 1990 404 19.', NULL, NULL),
(9, 'plugins_ecommerce_customer_new_order_status', '0', NULL, NULL),
(10, 'plugins_ecommerce_admin_new_order_status', '0', NULL, NULL),
(11, 'theme', 'martfury', NULL, NULL),
(12, 'admin_logo', 'general/logo-light.png', NULL, NULL),
(97, 'language_hide_default', '1', NULL, NULL),
(98, 'language_switcher_display', 'dropdown', NULL, NULL),
(99, 'language_display', 'all', NULL, NULL),
(100, 'language_hide_languages', '[]', NULL, NULL),
(111, 'ecommerce_store_name', 'Martfury', NULL, NULL),
(112, 'ecommerce_store_phone', '1800979769', NULL, NULL),
(113, 'ecommerce_store_address', '502 New Street', NULL, NULL),
(114, 'ecommerce_store_state', 'Brighton VIC', NULL, NULL),
(115, 'ecommerce_store_city', 'Brighton VIC', NULL, NULL),
(116, 'ecommerce_store_country', 'AU', NULL, NULL),
(117, 'theme-martfury-site_title', 'Enjoy -  Ecommerce system', NULL, NULL),
(118, 'theme-martfury-copyright', '© 2022 Enjoy. All Rights Reserved.', NULL, NULL),
(119, 'theme-martfury-favicon', 'general/favicon.png', NULL, NULL),
(120, 'theme-martfury-logo', 'general/logo.png', NULL, NULL),
(121, 'theme-martfury-welcome_message', 'Welcome to Enjoy Online Shopping Store!', NULL, NULL),
(122, 'theme-martfury-address', '502 New Street, Brighton VIC, Australia', NULL, NULL),
(123, 'theme-martfury-hotline', '1800 97 97 69', NULL, NULL),
(124, 'theme-martfury-email', 'contact@enjoy.co', NULL, NULL),
(125, 'theme-martfury-payment_methods', '[null,\"general\\/payment-method-1.jpg\",\"general\\/payment-method-2.jpg\",\"general\\/payment-method-3.jpg\",\"general\\/payment-method-4.jpg\",\"general\\/payment-method-5.jpg\"]', NULL, NULL),
(126, 'theme-martfury-newsletter_image', 'general/newsletter.jpg', NULL, NULL),
(127, 'theme-martfury-homepage_id', '1', NULL, NULL),
(128, 'theme-martfury-blog_page_id', '6', NULL, NULL),
(129, 'theme-martfury-cookie_consent_message', 'Your experience on this site will be improved by allowing cookies', NULL, NULL),
(130, 'theme-martfury-cookie_consent_learn_more_url', 'http://martfury.test/cookie-policy', NULL, NULL),
(131, 'theme-martfury-cookie_consent_learn_more_text', 'Cookie Policy', NULL, NULL),
(132, 'theme-martfury-number_of_products_per_page', '40', NULL, NULL),
(133, 'theme-martfury-product_feature_1_title', 'Shipping worldwide', NULL, NULL),
(134, 'theme-martfury-product_feature_1_icon', 'icon-network', NULL, NULL),
(135, 'theme-martfury-product_feature_2_title', 'Free 7-day return if eligible, so easy', NULL, NULL),
(136, 'theme-martfury-product_feature_2_icon', 'icon-3d-rotate', NULL, NULL),
(137, 'theme-martfury-product_feature_3_title', 'Supplier give bills for this product.', NULL, NULL),
(138, 'theme-martfury-product_feature_3_icon', 'icon-receipt', NULL, NULL),
(139, 'theme-martfury-product_feature_4_title', 'Pay online or when receiving goods', NULL, NULL),
(140, 'theme-martfury-product_feature_4_icon', 'icon-credit-card', NULL, NULL),
(141, 'theme-martfury-contact_info_box_1_title', 'Contact Directly', NULL, NULL),
(142, 'theme-martfury-contact_info_box_1_subtitle', 'contact@martfury.com', NULL, NULL),
(143, 'theme-martfury-contact_info_box_1_details', '(+004) 912-3548-07', NULL, NULL),
(144, 'theme-martfury-contact_info_box_2_title', 'Headquarters', NULL, NULL),
(145, 'theme-martfury-contact_info_box_2_subtitle', '17 Queen St, Southbank, Melbourne 10560, Australia', NULL, NULL),
(146, 'theme-martfury-contact_info_box_2_details', '', NULL, NULL),
(147, 'theme-martfury-contact_info_box_3_title', 'Work With Us', NULL, NULL),
(148, 'theme-martfury-contact_info_box_3_subtitle', 'Send your CV to our email:', NULL, NULL),
(149, 'theme-martfury-contact_info_box_3_details', 'career@martfury.com', NULL, NULL),
(150, 'theme-martfury-contact_info_box_4_title', 'Customer Service', NULL, NULL),
(151, 'theme-martfury-contact_info_box_4_subtitle', 'customercare@martfury.com', NULL, NULL),
(152, 'theme-martfury-contact_info_box_4_details', '(800) 843-2446', NULL, NULL),
(153, 'theme-martfury-contact_info_box_5_title', 'Media Relations', NULL, NULL),
(154, 'theme-martfury-contact_info_box_5_subtitle', 'media@martfury.com', NULL, NULL),
(155, 'theme-martfury-contact_info_box_5_details', '(801) 947-3564', NULL, NULL),
(156, 'theme-martfury-contact_info_box_6_title', 'Vendor Support', NULL, NULL),
(157, 'theme-martfury-contact_info_box_6_subtitle', 'vendorsupport@martfury.com', NULL, NULL),
(158, 'theme-martfury-contact_info_box_6_details', '(801) 947-3100', NULL, NULL),
(159, 'theme-martfury-number_of_cross_sale_products_in_cart_page', '7', NULL, NULL),
(160, 'theme-martfury-logo_in_the_checkout_page', 'general/logo-dark.png', NULL, NULL),
(161, 'theme-martfury-logo_in_invoices', 'general/logo-dark.png', NULL, NULL),
(162, 'theme-martfury-logo_vendor_dashboard', 'general/logo-dark.png', NULL, NULL),
(165, 'theme-martfury-social-name-1', 'Facebook', NULL, NULL),
(166, 'theme-martfury-social-url-1', 'https://www.facebook.com/', NULL, NULL),
(167, 'theme-martfury-social-icon-1', 'fa-facebook', NULL, NULL),
(168, 'theme-martfury-social-color-1', '#3B5999', NULL, NULL),
(169, 'theme-martfury-social-name-2', 'Twitter', NULL, NULL),
(170, 'theme-martfury-social-url-2', 'https://www.twitter.com/', NULL, NULL),
(171, 'theme-martfury-social-icon-2', 'fa-twitter', NULL, NULL),
(172, 'theme-martfury-social-color-2', '#55ACF9', NULL, NULL),
(173, 'theme-martfury-social-name-3', 'Instagram', NULL, NULL),
(174, 'theme-martfury-social-url-3', 'https://www.instagram.com/', NULL, NULL),
(175, 'theme-martfury-social-icon-3', 'fa-instagram', NULL, NULL),
(176, 'theme-martfury-social-color-3', '#E1306C', NULL, NULL),
(177, 'theme-martfury-social-name-4', 'Youtube', NULL, NULL),
(178, 'theme-martfury-social-url-4', 'https://www.youtube.com/', NULL, NULL),
(179, 'theme-martfury-social-icon-4', 'fa-youtube', NULL, NULL),
(180, 'theme-martfury-social-color-4', '#FF0000', NULL, NULL),
(181, 'theme-martfury-vi-copyright', '© 2022 Martfury. Tất cả quyền đã được bảo hộ.', NULL, NULL),
(182, 'theme-martfury-vi-welcome_message', 'Chào mừng đến với Martfury - Cửa Hàng Mua Sắm Online!', NULL, NULL),
(183, 'theme-martfury-vi-homepage_id', '1', NULL, NULL),
(184, 'theme-martfury-vi-blog_page_id', '6', NULL, NULL),
(185, 'theme-martfury-vi-cookie_consent_message', 'Trải nghiệm của bạn trên trang web này sẽ được cải thiện bằng cách cho phép cookie ', NULL, NULL),
(186, 'theme-martfury-vi-cookie_consent_learn_more_url', 'http://martfury.test/cookie-policy', NULL, NULL),
(187, 'theme-martfury-vi-cookie_consent_learn_more_text', 'Chính sách cookie', NULL, NULL),
(188, 'theme-martfury-vi-product_feature_1_title', 'Vận chuyển toàn cầu', NULL, NULL),
(189, 'theme-martfury-vi-product_feature_2_title', 'Miễn phí hoàn hàng 7 ngày', NULL, NULL),
(190, 'theme-martfury-vi-product_feature_3_title', 'Nhà cung cấp sẽ cấp hóa đơn cho sản phẩm này', NULL, NULL),
(191, 'theme-martfury-vi-product_feature_4_title', 'Thanh toán online hoặc trực tiếp', NULL, NULL),
(192, 'media_random_hash', '0acd8adfaf6cb28d7f59dd3487385ede', NULL, NULL),
(201, 'licensed_to', 'codyh8', NULL, NULL),
(202, 'theme-martfury-show_site_name', '0', NULL, NULL),
(203, 'theme-martfury-seo_title', '', NULL, NULL),
(204, 'theme-martfury-seo_description', '', NULL, NULL),
(205, 'theme-martfury-seo_og_image', '', NULL, NULL),
(206, 'theme-martfury-preloader_enabled', 'no', NULL, NULL),
(207, 'theme-martfury-enable_newsletter_popup', 'yes', NULL, NULL),
(208, 'theme-martfury-newsletter_show_after_seconds', '10', NULL, NULL),
(209, 'theme-martfury-facebook_chat_enabled', 'no', NULL, NULL),
(210, 'theme-martfury-facebook_page_id', '', NULL, NULL),
(211, 'theme-martfury-facebook_comment_enabled_in_post', 'no', NULL, NULL),
(212, 'theme-martfury-facebook_app_id', '', NULL, NULL),
(213, 'theme-martfury-facebook_admins', '[[{\"key\":\"text\",\"value\":null}]]', NULL, NULL),
(214, 'theme-martfury-facebook_comment_enabled_in_product', 'no', NULL, NULL),
(215, 'theme-martfury-primary_font', 'Work Sans', NULL, NULL),
(216, 'theme-martfury-primary_color', '#314686', NULL, NULL),
(217, 'theme-martfury-secondary_color', '#EB9C57', NULL, NULL),
(218, 'theme-martfury-header_text_color', '#FFFFFF', NULL, NULL),
(219, 'theme-martfury-header_text_hover_color', '#FFFFFF', NULL, NULL),
(220, 'theme-martfury-header_text_accent_color', '#000000', NULL, NULL),
(221, 'theme-martfury-header_button_background_color', '#EB9C57', NULL, NULL),
(222, 'theme-martfury-header_button_text_color', '#FFFFFF', NULL, NULL),
(223, 'theme-martfury-button_text_color', '#FFFFFF', NULL, NULL),
(224, 'theme-martfury-product_feature_5_title', '', NULL, NULL),
(225, 'theme-martfury-product_feature_5_icon', '', NULL, NULL),
(226, 'theme-martfury-social-name-5', '', NULL, NULL),
(227, 'theme-martfury-social-icon-5', 'fa-500px', NULL, NULL),
(228, 'theme-martfury-social-url-5', '', NULL, NULL),
(229, 'theme-martfury-social-color-5', '#000000', NULL, NULL),
(230, 'theme-martfury-social-name-6', '', NULL, NULL),
(231, 'theme-martfury-social-icon-6', 'fa-500px', NULL, NULL),
(232, 'theme-martfury-social-url-6', '', NULL, NULL),
(233, 'theme-martfury-social-color-6', '#000000', NULL, NULL),
(234, 'theme-martfury-social-name-7', '', NULL, NULL),
(235, 'theme-martfury-social-icon-7', 'fa-500px', NULL, NULL),
(236, 'theme-martfury-social-url-7', '', NULL, NULL),
(237, 'theme-martfury-social-color-7', '#000000', NULL, NULL),
(238, 'theme-martfury-social-name-8', '', NULL, NULL),
(239, 'theme-martfury-social-icon-8', 'fa-500px', NULL, NULL),
(240, 'theme-martfury-social-url-8', '', NULL, NULL),
(241, 'theme-martfury-social-color-8', '#000000', NULL, NULL),
(242, 'theme-martfury-social-name-9', '', NULL, NULL),
(243, 'theme-martfury-social-icon-9', 'fa-500px', NULL, NULL),
(244, 'theme-martfury-social-url-9', '', NULL, NULL),
(245, 'theme-martfury-social-color-9', '#000000', NULL, NULL),
(246, 'theme-martfury-social-name-10', '', NULL, NULL),
(247, 'theme-martfury-social-icon-10', 'fa-500px', NULL, NULL),
(248, 'theme-martfury-social-url-10', '', NULL, NULL),
(249, 'theme-martfury-social-color-10', '#000000', NULL, NULL),
(250, 'theme-martfury-number_of_posts_in_a_category', '12', NULL, NULL),
(251, 'theme-martfury-number_of_posts_in_a_tag', '12', NULL, NULL),
(252, 'theme-martfury-payment_methods_link', '', NULL, NULL),
(253, 'theme-martfury-show_featured_brands_on_products_page', 'yes', NULL, NULL),
(254, 'theme-martfury-show_recommend_items_on_products_page', 'yes', NULL, NULL),
(255, 'theme-martfury-number_of_cross_sale_product', '4', NULL, NULL),
(256, 'theme-martfury-max_filter_price', '100000', NULL, NULL),
(257, 'theme-martfury-cookie_consent_enable', 'yes', NULL, NULL),
(258, 'theme-martfury-cookie_consent_style', 'full-width', NULL, NULL),
(259, 'theme-martfury-cookie_consent_button_text', 'Allow cookies', NULL, NULL),
(260, 'theme-martfury-cookie_consent_background_color', '#000000', NULL, NULL),
(261, 'theme-martfury-cookie_consent_text_color', '#FFFFFF', NULL, NULL),
(262, 'theme-martfury-cookie_consent_max_width', '1170', NULL, NULL),
(263, 'admin_email', '[]', NULL, NULL),
(264, 'time_zone', 'UTC', NULL, NULL),
(265, 'locale_direction', 'ltr', NULL, NULL),
(266, 'enable_send_error_reporting_via_email', '0', NULL, NULL),
(267, 'admin_favicon', '', NULL, NULL),
(268, 'login_screen_backgrounds', '[]', NULL, NULL),
(269, 'admin_title', 'Enjoy', NULL, NULL),
(270, 'rich_editor', 'ckeditor', NULL, NULL),
(271, 'enable_change_admin_theme', '0', NULL, NULL),
(272, 'enable_cache', '0', NULL, NULL),
(273, 'cache_time', '10', NULL, NULL),
(274, 'cache_admin_menu_enable', '0', NULL, NULL),
(275, 'google_site_verification', '', NULL, NULL),
(276, 'cache_time_site_map', '3600', NULL, NULL),
(277, 'show_admin_bar', '1', NULL, NULL),
(278, 'enable_faq_schema', '0', NULL, NULL),
(279, 'google_analytics', '', NULL, NULL),
(280, 'analytics_view_id', '', NULL, NULL),
(281, 'analytics_service_account_credentials', '', NULL, NULL),
(282, 'newsletter_mailchimp_api_key', '', NULL, NULL),
(283, 'newsletter_mailchimp_list_id', '', NULL, NULL),
(284, 'newsletter_sendgrid_api_key', '', NULL, NULL),
(285, 'newsletter_sendgrid_list_id', '', NULL, NULL),
(286, 'enable_captcha', '0', NULL, NULL),
(287, 'captcha_type', 'v2', NULL, NULL),
(288, 'captcha_hide_badge', '0', NULL, NULL),
(289, 'captcha_site_key', '', NULL, NULL),
(290, 'captcha_secret', '', NULL, NULL),
(291, 'locale', 'en', NULL, NULL),
(292, 'default_admin_theme', 'default', NULL, NULL),
(293, 'admin_locale_direction', 'ltr', NULL, NULL);


/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;